use `gunzip -c` instead of `zcat` which only supports .Z and not .gz on Mac OS X

diff --git a/demo/mnist/do-pixelngram-test b/demo/mnist/do-pixelngram-test
--- a/demo/mnist/do-pixelngram-test
+++ b/demo/mnist/do-pixelngram-test
@@ -14,12 +14,12 @@ test -e t10k-labels-idx1-ubyte.gz || {
 
 test -e t10k-images-idx3-ubyte.gz || {
   echo "ERROR: you need to download t10k-images-idx3-ubyte.gz" 1>&2
-  echo "ERROR: from http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz" 1>&2 
+  echo "ERROR: from http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz" 1>&2
   exit 1
 }
 
 paste -d' '                                                     \
-  <(zcat t10k-labels-idx1-ubyte.gz | ./extract-labels)          \
-  <(zcat t10k-images-idx3-ubyte.gz |                            \
+  <(gunzip -c t10k-labels-idx1-ubyte.gz | ./extract-labels)     \
+  <(gunzip -c t10k-images-idx3-ubyte.gz |                       \
     ./extractpixels | ./pixelngrams) |                          \
 ../../vowpalwabbit/vw -t -i $1.model -p $1.test.predictions
