update test

diff --git a/demo/mnist/do-test b/demo/mnist/do-test
--- a/demo/mnist/do-test
+++ b/demo/mnist/do-test
@@ -1,10 +1,10 @@
 #! /bin/zsh
 
-#test -e $1.model || {
-#  echo "ERROR: you need to train a model" 1>&2
-#  echo "ERROR: run do-${1}-train in this directory" 1>&2
-#  exit 1
-#}
+test -e $1.model || {
+  echo "ERROR: you need to train a model" 1>&2
+  echo "ERROR: run do-${1}-train in this directory" 1>&2
+  exit 1
+}
 
 test -e t10k-labels-idx1-ubyte.gz || {
   echo "ERROR: you need to download t10k-labels-idx1-ubyte.gz" 1>&2
@@ -20,5 +20,5 @@ test -e t10k-images-idx3-ubyte.gz || {
 
 paste -d' '                                                     \
   <(gunzip -c t10k-labels-idx1-ubyte.gz | ./extract-labels)          \
-  <(gunzip -c t10k-images-idx3-ubyte.gz | ./extractfeatures) > mnist.t
-#../../vowpalwabbit/vw -t -i $1.model -p $1.test.predictions
+  <(gunzip -c t10k-images-idx3-ubyte.gz | ./extractfeatures) |       \
+../../vowpalwabbit/vw -t -i $1.model -p $1.test.predictions
