add format check pipeline

diff --git a/utl/clang-format b/utl/clang-format
--- a/utl/clang-format
+++ b/utl/clang-format
@@ -2,20 +2,27 @@
 
 # Usage (from repo root):
 # "./utl/clang-format fix" formats your code.
+# "./utl/clang-format advise" outputs formatting issues but exits with a zero exit code.
 # "./utl/clang-format check" exits with non-zero if your code isn't formatted correctly.
 # Intended to be used with clang-format 7.0.1.
 
+failed_format_test=false
 for VW_FILE in $(find vowpalwabbit -type f -name '*.cc' -o -name '*.h'); do
-
-    if [ "$1" = check ]; then
-       diff $VW_FILE <(clang-format $VW_FILE);
-       if [ $? -ne 0 ]; then
-       	  echo "Run \"./utl/clang-format fix\""
-       fi
+    if [ "$1" = check ] || [ "$1" = advise ]; then
+        diff $VW_FILE <(clang-format $VW_FILE);
+        if [ $? -ne 0 ]; then
+            echo "Run \"./utl/clang-format fix\""
+            if [ "$1" = check ]; then
+                failed_format_test=true
+            fi
+        fi
     fi
 
     if [ "$1" = fix ]; then
        clang-format -i $VW_FILE;
     fi
-
 done
+
+if [ "$failed_format_test" = true ] ; then
+    exit 1
+fi
