Move to github action based

diff --git a/utl/clang-format b/utl/clang-format
--- a/utl/clang-format
+++ b/utl/clang-format
@@ -4,7 +4,8 @@
 # "./utl/clang-format fix" formats your code.
 # "./utl/clang-format check" exits with non-zero if your code isn't formatted correctly.
 # Intended to be used with clang-format 7.0.1.
-# Set environment variable AZ_PIPELINE_LOGGING to output logging that Azure pipelines will interpret as a warning.
+# Set environment variable GH_WORKFLOW_LOGGING to output logging that Azure pipelines will interpret as a warning.
+# Set environment variable WARNING_AS_ERROR to output logging that Azure pipelines will interpret as a warning.
 
 for VW_FILE in $(find vowpalwabbit -type f -name '*.cc' -o -name '*.h'); do
 
@@ -12,8 +13,8 @@ for VW_FILE in $(find vowpalwabbit -type f -name '*.cc' -o -name '*.h'); do
         diff $VW_FILE <(clang-format $VW_FILE);
         if [ $? -ne 0 ]; then
             ISSUE_FOUND="true"
-            if [[ -v AZ_PIPELINE_LOGGING ]]; then
-                echo "##vso[task.logissue type=warning;sourcepath=$VW_FILE;] Formatting issues found in $VW_FILE"
+            if [[ -v GH_WORKFLOW_LOGGING ]]; then
+                echo "::warning file=$VW_FILE::Formatting issues found in $VW_FILE"
             fi
         fi
     fi
@@ -26,4 +27,8 @@ done
 
 if [[ -v ISSUE_FOUND ]]; then
     echo -e "\nFormatting issues found:\n\tRun \"./utl/clang-format fix\""
+    if [[ -v WARNING_AS_ERROR ]]; then
+        echo -e "\nTreating as failure because WARNING_AS_ERROR was set"
+        exit 1
+    fi
 fi
