fix: Update clang-format script with docker/podman version from rlclientlib (#4028)
* Update clang-format script with docker/podman version from rlclientlib

* Update lint error message

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -105,15 +105,21 @@ jobs:
         if: github.event_name == 'pull_request'
         shell: bash
         run: |
+          if [[ ! -f .clang-format ]]; then
+            echo "Cannot find .clang-format file!"
+            exit 1
+          fi
           git diff origin/master...HEAD -U0 --no-color | clang-format-diff -r '^.*\.(cc|h)$' -p1 > clang_format_diff.txt
           if [ -s clang_format_diff.txt ]; then
             cat clang_format_diff.txt
             echo "::error:: Formatting issues found"
             echo "To fix:"
-            echo -e "\tEnsure there is an upstream remote that points to: https://github.com/VowpalWabbit/vowpal_wabbit.git"
-            echo -e "\tRun: \"git fetch upstream\""
-            echo -e "\tUse Docker: https://gist.github.com/jackgerrits/2736da5ffff871f7830aed6b55c0c73e"
-            echo -e "\tOr, Run: \"git diff upstream/master...HEAD -U0 --no-color | clang-format-diff -r '^.*\.(cc|h)$' -p1 -i\""
+            echo -e "\tUse the clang-format.sh script in docker mode:"
+            echo -e "\t\tRun: \"./utl/clang-format.sh docker fix\""
+            echo -e "\tOr, install the right verson of clang-format locally"
+            echo -e "\t\tRun: \"git diff upstream/master...HEAD -U0 --no-color | clang-format-diff -r '^.*\.(cc|h)$' -p1 -i\""
+            echo -e "\tBe sure to check your version of clang-format. The version used here is..."
+            clang-format --version
             exit 1
           else
             echo "No formatting issues found in the PR diff."
